baseURL = "sorrowcode.dev"
languageCode = "en-us"
title = "WIP"
#theme = "hugo-theme-nix"

[params]
  Name = "Mathias Darscht"
  HeaderUsername = "sorrowcode"
  HeaderHostname = "github"
  About = "idk what to say about myself"
  #ProfilePicture = "profile_picture_url"
  Email = "your_email"

[menu]
  [[menu.header]]
    identifier = "post"
    name = "posts"
    weight = 0