baseURL = "sorrowcode.dev"
languageCode = "en-us"
title = "WIP"
#theme = "nightfall"

[module]
[[module.imports]]
    path = 'github.com/LordMathis/hugo-theme-nightfall'

[params]
user = "sorrowcode"
hostname = "sorrowcode.github.io"
footerHtml = 'sic mundus creatus est'

  [params.author]
    name = "Mathias Darscht"
    email = "hugo@example.com"

[menu]
  [[menu.header]]
    name = "posts"
    weight = 0
    url = "/posts"
